version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

sphinx:
  configuration: 2206_OpenFOAM_Training/source/conf.py

python:
  install:
    - requirements: 2206_OpenFOAM_Training/source/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - doc